project: code-query
program: scripts/tune.py
method: random
metric:
  name: valid/loss
  goal: minimize
parameters:
  encoder_type:
    value: nbow
  code_lang:
    value: python
  learning_rate:
    distribution: log_uniform
    min: -8
    max: -1
  gradient_clip_val:
    distribution: uniform
    min: 0.80
    max: 1.60
  embedding_dim:
    values: [16, 32, 64, 128]
  encoding_dim:
    values: [16, 32, 64, 128]
  encoder_dropout:
    distribution: uniform
    min: 0.00
    max: 0.50
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--max_epochs"
  - "1"
  - ${args}
